pipeline {
    agent {
        label 'linux-node-1'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }
    environment {
        APP_ENV = 'production'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building artifacts..."
            }
        }
        stage('Test') {
            steps {
                echo "Executing unit tests..."
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying release..."
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
